### ISSUE TITLE
ImplicitAccessTokenProvider with user's authentication and approval

### ISSUE THREAD

**Issue by adolfoweloy** [spring-projects/spring-security-oauth#1127]
I am writing an OAuth 2.0 client application and I am trying to use `ImplicitAccessTokenProvider`. I perfectly understood that for web applications the recommended is to use `AuthorizationCodeAccessTokenProvider` (it also makes sense as per OAuth 2.0 specification). But I want to know how to use `ImplicitAccessTokenProvider`.

Does anybody have written any Client application which relies on `ImplicitAccessTokenProvider`? 

I would like to understand how the Authorization Server (I am also providing an Authorization Server with SSO2) could be customized to support Implicit grant type by using `/oauth/token` endpoint with POST HTTP method.

Even if the client is a native one, we need the Resource Owner to be authenticated by Authorization Server and we also need the Resource Owner to grant permissions to the client application so a redirect is done returning the access token as a fragment.

It seems to me that the following snippet of code from `ImplicitAccessTokenProvider.obtainAccessToken` does not follows RFC 6749 to support Implicit grant type (am I right?).

```java
ImplicitResourceDetails resource = (ImplicitResourceDetails) details;
try {
	// We can assume here that the request contains all the parameters needed for authentication etc.
	OAuth2AccessToken token = retrieveToken(request,
			resource, getParametersForTokenRequest(resource, request), getHeadersForTokenRequest(request));
	if (token==null) {
		// Probably an authenticated request, but approval is required.  TODO: prompt somehow?
		throw new UserRedirectRequiredException(resource.getUserAuthorizationUri(), request.toSingleValueMap());				
	}
	return token;
}
catch (UserRedirectRequiredException e) {
	// ... but if it doesn't then capture the request parameters for the redirect
	throw new UserRedirectRequiredException(e.getRedirectUri(), request.toSingleValueMap());
}
```

Another reason I would like to better understand the usage of this class, is because I want to document the usage of this with some examples.

**Comment by phxism** [comment]
For now,I can not find any way to use oauth2 with Implicit in OAuth2RestTemplate ...

**Comment by jgrandja** [comment]
@adolfoweloy @phxism The `implicit` grant is NOT recommended and in fact deprecated in [OAuth 2.1](https://aaronparecki.com/2019/12/12/21/its-time-for-oauth-2-dot-1).

Also, this feels like a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-security-oauth#contributing-to-spring-security-oauth), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it).
