### ISSUE TITLE
Add support for EC based JWK keys

### ISSUE THREAD

**Issue by duergner** [spring-projects/spring-security-oauth#1159]
The `spring-security-jwt` project currently does not offer any support for Elliptic Curves based signatures. This could be added  by an `EllipticCurveVerifier` similar to the existing `RsaVerifier`. JCE has support for EC based signatures as well.

Once support for EC based signatures is added to `spring-security-jwt` `spring-security-oauth2` could be extended to read EC based keys from a JWK source. This would require adding a new `EcJwkDefinition` class and mainly extend `JwkDefinitionSource` as well as `JwkSetConverter` to also handle EC keys beside the already supported RSA keys.

**Comment by duergner** [comment]
I created a first draft implementation for the extension to `spring-security-jwt` at: https://github.com/duergner/spring-security-oauth/commit/d12020a31c38677c0001b588adafff5741fed448 

A first draft for potential changes to `spring-security-oauth2` can be found at https://github.com/duergner/spring-security-oauth/commit/d7835a999e12dd89a2fa29fba66f2910684d9629

**Comment by duergner** [comment]
@rwinch I opened the two PRs to deliver this feature. Would be great to get feedback on what should be done in addition to get it merged.

I wasn't really sure about what type of tests you would expect to be in place for this e.g.

**Comment by jgrandja** [comment]
@duergner Thank you for submitting both PR's.

As an FYI, this project is in maintenance mode as our efforts our focused in the new OAuth/OIDC support (and JWT/JOSE) in Spring Security 5.0. Therefore, we are only accepting bug fixes and minor enhancements at this time.

I did take a quick look at both PR's and at first glance looks like it will be a clean merge. However, this will have to wait until 2.3 is released because of the new artifacts. I'm not sure when 2.3 will be released as of now as all our cycles are going into Spring Security 5.0 which is planned to be released on Nov 6. If I get any spare cycles before than I will take a look at the PR's in detail.

In the meantime, please add tests to both PR's.

Thanks for your efforts!

**Comment by adolfoweloy** [comment]
@jgrandja, @duergner 
have you noticed that travis checking are breaking because of an environment variable?

**Comment by jgrandja** [comment]
@adolfoweloy @duergner The Travis CI broken build issue is resolved via 11f24d6470d5241d9d167e0fce6756190e66170e

**Comment by duergner** [comment]
@jgrandja I pushed an update to both PRs that should contain tests covering the new features. Would be great to get some feedback whether it is sufficient now to be ready for merging.

**Comment by jgrandja** [comment]
@duergner I'll take a look at this next week as I'm heads down with some tasks to meet the Spring Security M5 release scheduled for next Tue.

**Comment by phaninra** [comment]
Thanks for adding the EC support. I'm unable to figure out how to hook this into my oauth flow. There's an `EllipticCurveVerifier`  but I could not find any Signer. Also, how would one create a Signer and a Verifier from static EC key-pair?
