### ISSUE TITLE
cannot use a custom httpclient when using spring-oauth2-tests-client ?

### ISSUE THREAD

**Issue by majinding** [spring-projects/spring-security-oauth#1256]
I have modified the authorized address on the official spring-oauth2-tests-client basis

![1](https://user-images.githubusercontent.com/2681645/34330673-5a812edc-e95a-11e7-91c7-29e8e17c175e.png)

![2](https://user-images.githubusercontent.com/2681645/34330692-82d78fb6-e95a-11e7-8c19-8f9ad3d72f9f.png)

According to the operation as shown in figure, the request failed, but when using the postman calls a success, so I like to do the request and reply headers output under the contrast
when I debug after , found that does not use okhttp invoked, found the request or SimpleClientHttpRequestFactory use, add LogRequestInterceptor no execution

 want to ask how to add Interceptor check send header information ?
 How do I use okhttpclient  ?

**Comment by sciack** [comment]
Inspecting the code of ``OAuth2RestTemplate`` looks like that when asks for an OAuth2 token, a new ``RestTemplate`` is created (see class ``OAuth2AccessTokenSupport``), without using any of the customization done on the OAuth2RestTemplate.
I have the same problem using custom X509 certificate and I've to configure them in the Default HTTPS connection, instead of creating an ``HTTPClientComponentHttpRequestFactory``.

**Comment by majinding** [comment]
It's been a long time,
Should be configured with a different domain name in host
