### ISSUE TITLE
Spring Security OAuth2 social 

### ISSUE THREAD

**Issue by cheese10yun** [spring-projects/spring-security-oauth#1482]
I have a question about setting up Facebook yml.

The link I refer to is https://spring.io/guides/tutorials/spring-boot-oauth2/.

If you set yml as below, the default profile information will not be passed.

According to the Facebook Document, https://developers.facebook.com/docs/facebook-login/permissions#reference-default

The following fields are provided as standard.

* id
* first_name
* last_name
* middle_name
* name
* name_format
* picture
* short_name

Why is not the above information coming over?

I solved it by setting yml as below.
```yml
facebook:
  client:
    clientId: <>
    clientSecret: <>
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope:
        - email
  resource:
    userInfoUri: https://graph.facebook.com/me?fields=id, name, email, picture
```
In the case of Google, basic information is passed.
But Facebook does not.

Sorry, I am not very good at english
I am always thanking Spring Open Source.

**Comment by jgrandja** [comment]
@cheese10yun I'm not sure why Facebook does not send back the other fields as default. Each provider is different so you really need to read their API docs to see how to correctly configure the client. You are correct though, with Facebook you need to provide the list of `fields` that you want returned in `userInfoUri`.

Have you tried the new OAuth 2.0 / OpenID Connect support we've been building since Spring Security 5.0? Here is a link to the sample for [Facebook](https://github.com/spring-projects/spring-security/tree/master/samples/boot/oauth2login#facebook-login).

I would highly encourage you to try Spring Security 5.x OAuth support as it provides a fairly complete feature list for Client and we're introducing Resource Server support in 5.1, which is scheduled for this Friday.

I'm going to close this issue as answered. If you feel you need more answer(s), we can re-open this.

**Comment by cheese10yun** [comment]
@jgrandja Thank you for your comment.
Spring Security 5.1 version is expected. I always appreciate Spring Open Source.
