### ISSUE TITLE
Getting OidcUser out of Authentication object

### ISSUE THREAD

**Issue by igler** [spring-projects/spring-security-oauth#1508]
Im am using the following code to get the OidcUser out of the Authentication object:

<pre><code>Assert.isTrue(authentication.getPrincipal() instanceof OidcUser, "Principal in authentication must be instance of OidcUser but was '" + authentication.getPrincipal().getClass().getName() + "'!");
OidcUser oidcUser = (OidcUser) authentication.getPrincipal();</code></pre>

From time to time I get an assert-exception that `authentication.getPrincipal()` is of type `java.lang.String`. Is there a better way to get the current OidcUser?

BTW, I am using spring-security 5.0.8.RELEASE that comes with spring-boot 2.0.5.RELEASE.
...
org.springframework.security:spring-security-config:jar:5.0.8.RELEASE:compile
org.springframework.security:spring-security-core:jar:5.0.8.RELEASE:compile
org.springframework.security:spring-security-oauth2-client:jar:5.0.8.RELEASE:compile
org.springframework.security:spring-security-oauth2-core:jar:5.0.8.RELEASE:compile

**Comment by jgrandja** [comment]
@igler You can obtain the `Principal` using `@AuthenticationPrincipal`.

```java
@GetMapping("/user")
public String userInfo(@AuthenticationPrincipal OAuth2User oauth2User) {
    ...
```

or if the `oauth2Login()` client is configure with an OIDC provider than:

```java
@GetMapping("/user")
public String userInfo(@AuthenticationPrincipal OidcUser oidcUser) {
    ...
```

I'm going to close this issue as I feel I have answered your question. For future reference, please log this issue with the [Spring Security](https://github.com/spring-projects/spring-security/issues) repo. Thanks!

**Comment by igler** [comment]
Getting a `org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalStateException: No primary or default constructor found for interface org.springframework.security.oauth2.core.oidc.user.OidcUser
` on one of my tests. The rest is working.

**Comment by jgrandja** [comment]
@igler It is quite difficult for me to troubleshoot if I cannot reproduce the issue on my end. To help me, please provide me a link to a repo with the relevant test that fails so I can reproduce and than resolve for you.

**Comment by igler** [comment]
Have sent you an invitation.

**Comment by jgrandja** [comment]
I checked out that branch and tried running `./mvnw clean test` but I get a failure with goal `pl.allegro:grunt-maven-plugin:1.5.1:grunt`.

What I was really looking for is a scaled down version of the app with detailed steps on how to reproduce the issue (or failed test). The shared repo has too many artifacts. Please provide a scaled down version.

**Comment by igler** [comment]
There is a new branch called 'reduced'. A `./mvnw clean test` should work and cause the exception.

**Comment by igler** [comment]
What is working is `@AuthenticationPrincipal OAuth2AuthenticationToken authToken` as parameter in controller-method and resolve `OidcUser ` by manually doing `OidcUser oidcUser = (OidcUser) authToken.getPrincipal();`

**Comment by jgrandja** [comment]
@igler Can you please resend the invite?

**Comment by igler** [comment]
Have send the invite again. New project, branch is master now. A ./mvnw clean test should work and cause the exception.

**Comment by jgrandja** [comment]
@igler `./mvnw clean test` produces the error in `ReservationRestTest.createReservationAsNL14User()`. However, when I try to debug in the IDE that same test method, it does not run because `testFetchingLocations()` fails before and `createReservationAsNL14User()` is dependent on it.

Again, to make things easier for me, I need a very slim app that reproduces the issue. Even if you have to re-create another isolated test on it's own. The current setup has way too much code that really is not efficient for me to help you troubleshoot.

I'm 99% sure your issue is with Spring Web MVC setup and Spring Security integration. To confirm this put a break-point in 

`org.springframework.security.config.annotation.web.configuration.WebMvcSecurityConfiguration.addArgumentResolvers()`

This method should get called which initializes `AuthenticationPrincipalArgumentResolver`. This is the resolver that resolves `@AuthenticationPrincipal` controller arguments.

If the `WebMvcSecurityConfiguration.addArgumentResolvers()` method is not called, which I suspect, that is the reason you are getting that error. I've seen this before and this is the root cause.

FYI, `@EnableWebSecurity` will `@Import` `SpringWebMvcImportSelector` which will load `WebMvcSecurityConfiguration`.

**Comment by igler** [comment]
Have debugged things and `WebMvcSecurityConfiguration.addArgumentResolvers()` is called. At the end of the method a `AuthenticationPrincipalArgumentResolver` is added (see attached screenshot).

![addargumentresolvers](https://user-images.githubusercontent.com/313565/47280017-9ab2eb00-d5d4-11e8-97c7-d1a4c08a8980.png)

Putting a breakpoint in `AuthenticationPrincipalArgumentResolver.resolveArgument` then this is never called during tests. I was thinking that this method is called when one of the parameters `@AuthenticationPrincipal OidcUser oidcUser` is resolved in one of the controllers.
