### ISSUE TITLE
How to set non-expired token in OAuth2?

### ISSUE THREAD

**Issue by phearun008** [spring-projects/spring-security-oauth#1812]
How to set non-expired token in OAuth2?

**Comment by vijayakumarbathini** [comment]
The following example OAuthV2 policy shows a long expiration time of 200 days for refresh tokens:

<OAuthV2 name="GenerateAccessToken">
    <Operation>GenerateAccessToken</Operation>
    <ExpiresIn>1800000</ExpiresIn> 
    <RefreshTokenExpiresIn>17280000000</RefreshTokenExpiresIn> 
    <SupportedGrantTypes>
      <GrantType>password</GrantType>
    </SupportedGrantTypes>
    <GenerateResponse enabled="true"/>
</OAuthV2>

**Comment by vijayakumarbathini** [comment]
The following example OAuthV2 policy shows a long expiration time of 200 days for refresh tokens:

`<OAuthV2 name="GenerateAccessToken">
    <Operation>GenerateAccessToken</Operation>
    <ExpiresIn>1800000</ExpiresIn> 
    <RefreshTokenExpiresIn>17280000000</RefreshTokenExpiresIn> 
    <SupportedGrantTypes>
      <GrantType>password</GrantType>
    </SupportedGrantTypes>
    <GenerateResponse enabled="true"/>
</OAuthV2>`

**Comment by jzheaux** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add more detail if you feel this is a genuine bug.
