### ISSUE TITLE
dynamic client config

### ISSUE THREAD

**Issue by asufty888** [spring-projects/spring-security-oauth#1821]
Working on a SAAS app with dynamic clients (rest-template, resource, etc).  Are there any examples or best practices for doing this?

**Comment by jgrandja** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
