### ISSUE TITLE
Consider removing `@Deprecated` to all the classes in 2.4.x

### ISSUE THREAD

**Issue by jebeaudet** [spring-projects/spring-security-oauth#1825]
Hi

I recently updated to 2.4.0 all happy to see the dependency to jackson 1 removed to find out more than 150 warnings in my codebase about deprecation. I know that this project is in maintenance mode but is a `@Deprecated` on every class really needed to convey the message? I personally think the notice on the readme and the blog posts you did are enough to alert your users of the future of this project.

What do you think? I'm talking about those 2 commits https://github.com/spring-projects/spring-security-oauth/commit/6234826671d75632d84c524da1dd8818cee1b4c2 and https://github.com/spring-projects/spring-security-oauth/commit/0e7baf7e91e145d8eb738d4a5e1cda94153b7b3d.

Thanks a lot!

**Comment by jgrandja** [comment]
@jebeaudet `@Deprecated` is required for all classes to clearly indicate to the user that they should start looking at alternative options then using this code/project. FYI, this project will retire in the near future. Please see this [announcement](https://spring.io/blog/2019/11/14/spring-security-oauth-2-0-roadmap-update#support-lifetime-for-spring-security-oauth-2-x).

**Comment by xak2000** [comment]
@jgrandja Can you please reconsider this decision?

I totally fine with this project EOL. But after updating to 2.4.0 I have billion of deprecation warnings in my project. :(

This project will not be removed from github and maven central, right? So it is totally fine to use it if it suffices for the application.

I already have an application (auth microservice) implemented with this project as a base, and it is too late to "migrate" (it's hard to use this word because "migrate" here virtually means writing from scratch) it to something else (especially considering there is no something else in the market with equal feature-set (I mean only "authorization server part" here, that is what I actually use, for resource-server part Spring Security 5 is totally fine and I migrated to it already in other microservices)) in the near feature, because it's very time-consuming task.

Do you really think that `@Deprecated` annotation is intended to be used like this? When the deprecated entity is **the project** and not some it's class/interface/field etc. This project is "deprecated" only in a sense that it will not be maintained, right? Each individual class of this project isn't deprecated in the literal sense of the word.

I think this annotation meant to be used for other purposes, like if some class/interface is deprecated and there is new class to be used. But all project? Isn't this too much?

What should I do now? Add `@SuppressWarnings("deprecation")` to every single class of my microservice? This is possible but can hide **real** usage of some deprecated API of some library (in opposite to intentional usage of `spring-security-oauth` dependency).

Maybe it's worth to be added to core classes/annotation of the project, like `@EnableAuthorizationServer`. But all of them?

**Comment by jebeaudet** [comment]
I obviously agree with you @xak2000. FWIW, I've ended up publishing an internal release with all the `@Deprecated` annotations removed [here](https://github.com/coveord/spring-security-oauth/tree/2.4.x-COVEO) if you're interested.

**Comment by jgrandja** [comment]
@jebeaudet @xak2000 

> I know that this project is in maintenance mode but is a `@Deprecated` on every class really needed to convey the message? I personally think the notice on the readme and the blog posts you did are enough to alert your users of the future of this project.

There are users that simply live in their IDE so it's very possible they won't see the notice on readme or blog posts. Having the classes `@Deprecated` will notify the user without fail. If we simply marked some of the core classes/interfaces/annotations then it still might get missed.

If you want to ignore the deprecation warnings you can try passing the JVM argument `-Xlint:none` or `-Xlint:-deprecation`.

After this project is officially retired and "opened up" to the community, you can easily revert those 2 commits then.
