### ISSUE TITLE
Authorize /oauth/authorize endpoint in the same way /oauth/token is secured.

### ISSUE THREAD

**Issue by abhisahai90** [spring-projects/spring-security-oauth#1833]
Currently /oauth/token endpoint is BY DEFAULT secured by Spring Security where as /oauth/authorize is not. I was trying to secure the /oauth/authorize endpoint in the same way /oauth/token endpoint is secured but not able to do so. 

protected void configure(HttpSecurity http) throws Exception {
String authorizationEndpoint = handlerMapping.getServletPath("/oauth/authorize");
http.authorizeRequests().antMatchers(tokenEndpointPath).fullyAuthenticated() ;
}

Is there something which I am missing here.

**Comment by rwinch** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
