### ISSUE TITLE
Could I customize invalid_client

### ISSUE THREAD

**Issue by fjnetinfo** [spring-projects/spring-security-oauth#1837]
For an invalid client, Exception will occur and output

{
    "error": "invalid_client",
    "error_description": "Bad client credentials"
}
when in json format.

Could I customize the json format, such as

{
    "error": "invalid_client",
    "error_description": "Bad client credentials",
    "server_time": 1232343434
}

**Comment by rwinch** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
