### ISSUE TITLE
How could I customize the renderer in case of exception?

### ISSUE THREAD

**Issue by Yogurt-lei** [spring-projects/spring-security-oauth#1838]
### Summary

How could I customize the renderer in case of exception?
when i use oauth2 with `allowFormAuthenticationForClients`.

1. `AuthorizationServerSecurityConfigurer#clientCredentialsTokenEndpointFilter` create `OAuth2AuthenticationEntryPoint` so i can't customize `OAuth2ExceptionRenderer` in it's parent `AbstractOAuth2SecurityExceptionHandler`
2. the `DefaultOAuth2ExceptionRenderer` have already fill some converters 

i can't find endpoint to customize the renderer, i need some help. plz.

### Expected Behavior
use customize render

when some things wrong , in `DefaultOAuth2ExceptionRenderer#writeWithMessageConverters`  i can call  my customize converter to convert exception with a customized json view
### Configuration

allowFormAuthenticationForClients = true 
### Version

spring-security-oauth2-2.3.4.RELEASE 
### Sample

Best Regards

**Comment by jgrandja** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
