### ISSUE TITLE
how to limit one connection/user with oAuth2

### ISSUE THREAD

**Issue by RobertoHuang** [spring-projects/spring-security-oauth#1839]
Hi
    I used Spring Security OAuth2 in my project, but i don't know how to limit one connection/user with oAuth2.  I can't tolerate one account to login on two devices. what can I do?
   
   look forward to receiving your reply. Thanks.

**Comment by jgrandja** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
