### ISSUE TITLE
Spring Boot OAuth2 Issue

### ISSUE THREAD

**Issue by ramugadde84** [spring-projects/spring-security-oauth#1849]
Hi I Built two applications one is Authorization Server which will give Access token that is working fine,
How i can Build Resource Server to access Authorization Server.

**Comment by rwinch** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
