### ISSUE TITLE
Access_token network issue

### ISSUE THREAD

**Issue by nichuanfang** [spring-projects/spring-security-oauth#1882]
Based on China's network environment and political factors, as a developer, when using your company's oauth2 service integration, after obtaining the authorization code issued by the provider, I found that I can't obtain the access_token through the http connection provided by you. Is it optimized for this problem? Thank you  very much.

ps. intelliJ IDEA 2019.1+win10
![image](https://user-images.githubusercontent.com/37105637/84632209-27848800-af21-11ea-9874-b470de5ba727.png)

**Comment by jgrandja** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-security-oauth#contributing-to-spring-security-oauth), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
