### ISSUE TITLE
Why is OAuth2Request in the extractAuthentication function in UserInfoTokenServices all assigned null

### ISSUE THREAD

**Issue by ChinaWangNing** [spring-projects/spring-security-oauth#1889]
### Summary
I want to use user-info-uri to get token information,But UserInfoTokenServices did not assign a value to resourceId,As a result, those without permission can also access

### Actual Behavior

UserInfoTokenServices did not assign a value to resourceId,As a result, those without permission can also access

### Expected Behavior

I hope I can assign resourceId without other configuration like client_id or client_secret

### Version

2.2.0.RELEASE

### Sample

![image](https://user-images.githubusercontent.com/30399735/89773748-1a59d300-db37-11ea-82a1-a85f2c2d1d95.png)
![image](https://user-images.githubusercontent.com/30399735/89773777-28a7ef00-db37-11ea-8af6-b11787398a7b.png)

**Comment by jgrandja** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-security-oauth#contributing-to-spring-security-oauth), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
