### ISSUE TITLE
How can we simply refresh the token validity when calling the authenticated endpoint

### ISSUE THREAD

**Issue by chentaikuang** [spring-projects/spring-security-oauth#1914]
Requirement: The calling interface will automatically refresh the Token validity time. The following steps are used:

1. Redis-based storage token

2. Modify DefaultoAuth2AccesToken to reset the setExpiration time
>oAuth2AccessToken.setExpiration(XX)

3. Call the storeAccessToken method

Problem: Objects are serialized differently after the valid time is modified, which causes the conn. Sadd in StoreAccesToken to constantly add new objects, causing the memory bloat problem

How can we simply refresh the token validity when calling the authenticated endpoint?

Looking forward to a reply

**Comment by jgrandja** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it).
