### ISSUE TITLE
Referenced document doesn't reference how to migrate deprecated BearerTokenExtractor

### ISSUE THREAD

**Issue by GregDomjan** [spring-projects/spring-security-oauth#1921]
https://github.com/spring-projects/spring-security-oauth/blob/6f2965368761d0f20027b62640e30c62844bcafd/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/authentication/BearerTokenExtractor.java#L32

**Comment by jgrandja** [comment]
@GregDomjan The new OAuth 2.0 support since Spring Security 5.0 is a complete re-write so classes in this project do not exist 1-1 in the new code base. You need to follow the [OAuth 2.0 Migration Guide](https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Migration-Guide) and the linked samples.
