### ISSUE TITLE
Failure when defining a custom ClientDetailsService in AuthorizationServerConfigurerAdapter

### ISSUE THREAD

**Issue by imod** [spring-projects/spring-security-oauth#336]
This is a copy of https://jira.spring.io/browse/SECOAUTH-451

While configuring a AuthorizationServer with `@EnableAuthorizationServer`and `AuthorizationServerConfigurerAdapter` I have the need to define a custom implementation of a `ClientDetailsService` which I tried like this:

```
@Override
public void configure(AuthorizationServerEndpointsConfigurer endpoints) throws Exception {
    ClientDetailsService clientDetailsService = getCustomClientDetailsService();
    endpoints.clientDetailsService(clientDetailsService);
}
```

although this seems work in the first place, one still also has to override:

```
@Override
public void configure(ClientDetailsServiceConfigurer clients) throws Exception {
    clients.inMemory().withClient()....
}
```

if not, the the following error will be thrown.
This makes it impossible to define a custom implementation of a `ClientDetailsService`.

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.clientDetailsService' defined in class path resource [org/springframework/security/oauth2/config/annotation/configuration/ClientDetailsServiceConfiguration.class]: Instantiation of bean failed;
nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public org.springframework.security.oauth2.provider.ClientDetailsService org.springframework.security.oauth2.config.annotation.configuration.ClientDetailsServiceConfiguration.clientDetailsService() throws java.lang.Exception] threw exception;
nested exception is java.lang.UnsupportedOperationException: Cannot build client services (maybe use inMemory() or jdbc()).
```

**Comment by xiejx618** [comment]
org.springframework.security.oauth2.config.annotation.configuration.ClientDetailsServiceConfiguration#clientDetailsService . it  creates a bean with name "clientDetailsService ".   And I custom my ClientDetailsService, and I use @Autowired private ClientDetailsService clientDetailsService to inject AuthorizationServerConfigurerAdapter. I found that it inject ClientDetailsServiceConfiguration#clientDetailsService Bean instead of my custom clientDetailsService .unless I use @Qualifier("clientDetailsServiceImpl") to inject my custom clientDetailsService

**Comment by maciejmiklas** [comment]
The clients-solution works, just do not Inject into your code classes like `AuthorizationEndpoint`, because this will change initialization order and configuerer will be ignored. Spring will create `AuthorizationEndpoint`  in first place with `InMemoryClientDetailsService` and after that the configurer will get created, but it's too late.
