### ISSUE TITLE
Handle all exceptions in @FrameworkEndpoint controllers

### ISSUE THREAD

**Issue by ractive** [spring-projects/spring-security-oauth#347]
The `@FrameworkEndpoint` controllers should handle all exceptions and return an appropriate response. If e.g. some DB exception occurs in the tokenStore while creating a new token, the `TokenEndpoint` does not catch and handle this exception (because it only handles OAuth2Exception and ClientRegistrationException exceptions) so that the standard container error html page is returned to the oauth client - which is wrong.

The `AbstractEndpoint` should handle *any* exception (and not just OAuth2Exceptions) with:

```java
@ExceptionHandler(Exception.class)
public ResponseEntity<Exception> handleException(Exception e) throws Exception {
	logger.info("Handling error: " + e.getClass().getSimpleName() + ", " + e.getMessage());
	return getExceptionTranslator().translate(e);
}
```

**Comment by dsyer** [comment]
Actually I'm not so sure that is a good idea since a browser client won't know what to do with the `ResponseEntity<Exception>`. It probably works fine in the `TokenEndpoint` though (only used by machines). Maybe can be adapted to work with the `AuthorizationEndpoint`, but shouldn't the application developer be responsible for setting up error handlers for generic errors?

**Comment by ractive** [comment]
I agree. The AuthorizationEndpoint is always called by a browser, isn't it?

The  TokenEndpoint definitively needs to handle all exceptions so that OAuth clients do not get an html-, but a proper JSON error reply.
