### ISSUE TITLE
DefaultOAuth2RequestValidator makes "scope" parameter mandatory

### ISSUE THREAD

**Issue by jbiblio** [spring-projects/spring-security-oauth#372]
The current implementation of `DefaultOAuth2RequestValidator` violates the OAuth RFC. 

If the client omits the "scope" parameter, the validator throws an exception, resulting in a denial of the request.

Please see chapter 3.3 of RFC 6749 [https://tools.ietf.org/html/rfc6749#section-3.3]: 

> The authorization and token endpoints **allow** the client to specify the scope of the access request using the "scope" request parameter.
> ...
> If the client **omits** the scope parameter when requesting authorization,
> (emphasizes by me)

Chapter 4.2.1 (Implicit Grant) declares the "scope" parameter as OPTIONAL.

I think the old implementation is more correct, since it compares requested and registered scopes only if needed.

Workaround: register a custom `OAuth2RequestValidator`.

**Comment by dsyer** [comment]
I think you are probably looking in the wrong place for the scope because clients send empty scope to the server all the time and get access tokens successfully. By the time the validator is called the `AuthorizationRequest` or `TokenRequest` have been created and potentially modified, so the scope will have been populated from somewhere (usually the default is the value registered with the client).

**Comment by jbiblio** [comment]
I see, thanks for the hint.
I'm unsure whether the RFC requires a client to have a scope pre-defined. It states a "default value", and I'd say a default value of `null` seems to be dangerous in most cases, so I think the validator works as intended; at least it might point to a possible trap.

**Comment by doom777** [comment]
sorry for reopening, but ``TokenRequest`` will not always be populated with a scope, since client sometimes doesn't have scopes at all (which spring documentation allows). I am not using scopes really in my app, since the only client is my own Android app, which gets full access. I am forced to put a scope on the request from client side, which the spec does not require as @jbiblio found. I don't even use the scope, it's just some random string in order to pass the check.

Please consider removing empty scope failure, or else consider use cases when it's needed and when it's not.

I know I can overwrite OAuth2RequestValidator with my own, so it's not a critical bug, but still should be done.

**Comment by jgrandja** [comment]
@doom777 As per spec in Section 3.3. Access Token Scope

> If the client omits the scope parameter when requesting
> authorization, the authorization server MUST either process the
> request using a pre-defined default value or fail the request
> indicating an invalid scope. The authorization server SHOULD
> document its scope requirements and default value (if defined).

So the default configuration of the Authorization Server is to fail if no scopes have been provided in the request which does conform to the spec as per above. However, you may override this behaviour by providing your own  `OAuth2RequestValidator`.

The default implementation of `DefaultOAuth2RequestValidator` does make sense as it provides another level of security by requiring the scope request parameter which is ultimately matched against the registered scopes for the client. Again, you can downgrade the level of security by providing your own implementation of `OAuth2RequestValidator` that doesn't validate the scope parameter and therefore you wouldn't be forced to pass this in the request.

**Comment by doom777** [comment]
What about refresh_token flow?

**Comment by jgrandja** [comment]
Yes for the refresh token flow the scope may be omitted in this case, and will default to the scope originally requested when the access token was obtained. Are you having an issue with this flow?

**Comment by doom777** [comment]
I am. I am not sending a scope for refresh_token, and it crashes on me. Sending a scope on refresh token also gives an exception

**Comment by dfcoffin** [comment]
What is the exception you are receiving when the refresh_token flow fails?  Are you seeing a stack dump when it fails?

**Comment by jgrandja** [comment]
@doom777 I'll need more info to be able to investigate this. Would you be able to provide a small sample that reproduces this issue?

**Comment by doom777** [comment]
@jgrandja yes, but not today
