### ISSUE TITLE
Use less aggressive check for existing beans to prevent early factory bean instantiation

### ISSUE THREAD

**Issue by holger-s** [spring-projects/spring-security-oauth#384]
I have a library that creates its own `PropertySourcesPlaceholderConfigurer` to fill some fields `@Value`. In projects without spring-security-oauth2 this works fine, but when I add spring-oauth2 all beans are created *before* these values are set. 
Debugging I found out that while the `AuthorizationServerEndpointsConfiguration$TokenKeyEndpointRegistrar` is processed all other beans are instantiated, without the `@Values` that I filled it. They are not updated later on, when my own `propertySourcePlaceholder` is added to the post processors.

The critical line in `TokenKeyEndpointRegistrar` is 200: 

```
 @Override
        public void postProcessBeanFactory(final ConfigurableListableBeanFactory beanFactory) throws BeansException {
            final String[] names = BeanFactoryUtils.beanNamesForTypeIncludingAncestors(beanFactory, SomeBean.class);
...
        }
```

This makes Spring instantiate all my beans.

How can I avoid this behaviour?

**Comment by dsyer** [comment]
I think `SomeBean` is `JwtTokenEnhancer` (I'm just confused because if it is, why not say so)? We could change the `BeanFactoryUtils` method to prevent some eager instantiation, but this hasn't caused problems for anyone else, so I think it would be better to try and understand your use case. I suspect it is perhaps the class where you put `@EnableAuthorizationServer` that is the problem, rather than the configuration that it is importing, but the devil is probably in the detail.

**Comment by holger-s** [comment]
Hi,
sorry yes it is the JwtAccessTokenConverter (that one was my from personal recreating example).
The use case is as follows (I am using an internal 3rd party library that does preprocessing this way, so I am sort of forced to use this):

  * There is a BeanDefinitionRegistryPostProcessor, that generates instances of AbstractFactoryBean<Object> for interfaces in my config and adds them to the BeanDefinitionRegistry
  * When BeanFactoryUtils comes along, it calls DefaultListableBeanFactory.doGetBeanNamesForType() and finds the factory beans in the beanDefinitionsList and calls AbstractBeanFactory.isTypeMatch() to check whether it can instantiate JwtAccessToken.
  * the bean type of these beans is AbstractFactoryBean, so AbstractAutowireCapableBeanFactory.getTypeForFactoryBean():803 is called, but it does not find a type for this bean
  * So AbstractBeanFactory.getTypeForFactoryBean():1418 is called, instantiating the bean of the factory
  * This is before the PropertySourcesPlaceholderConfigurer is picked up, because that is a regular BeanPostProcessor
  * Thus the @Value-annotated fields are not post-processed

I don't want to cause a change, if it is only caused by how I insert my beans in the lifecycle.

**Comment by dsyer** [comment]
`BeanDefinitionRegistryPostProcessor` is ringing alarm bells with me. You didn't if it (or its enclosing `@Configuration`) is the component that has `@EnableAuthorizationServer` then the problem is just that you are forcing Spring to create all that stuff super early. Extracting it into it's own configuration would fix that problem.

If that's not your problem, can you try patching `TokenKeyEndpointRegistrar` and using the other method in `BeanFactoryUtils` (with the boolean flags) to see if that helps? If it does we can just do that quickly here.

**Comment by holger-s** [comment]
(I think you were asking where the @Configuration is, the verb is missing though(.
Following structure: (-- is @Import)

ValueConfig -- MainConfig -- OAuthConfig (with @EnableAuthorizationServer)

And MainConfig has an annotation that imports the subclass of ImportBeanDefinitionRegistrar, that calls the BeanDefinitionRegistryPostProcessor, that adds these fields.

Should I seperate these?

**Comment by dsyer** [comment]
> Should I separate these?

Can you try putting the `BeanDefinitionRegistryPostProcessor` import in a separate class (e.g. a static inner class of `MainConfig` instead of the top level)?

**Comment by holger-s** [comment]
Same problem.

**Comment by holger-s** [comment]
String[] names = BeanFactoryUtils.beanNamesForTypeIncludingAncestors(beanFactory,
					JwtAccessTokenConverter.class, false, false);

Fixes the problem.

**Comment by holger-s** [comment]
So, are you going to change the call to not use eager initialization or is there a good reason not to? :-)

**Comment by dsyer** [comment]
No reason I can see not to change it. Pull requests definitely work for setting priorities BTW.
