### ISSUE TITLE
OAuth2Request.getGrantType() returns null for refresh_token grant

### ISSUE THREAD

**Issue by skampa** [spring-projects/spring-security-oauth#405]
Accessing the grant type via `OAuth2Request.getGrantType(…)` returns `null` if “refresh_token” grant is used. 
I’m using the `DefaultTokenServices` with JWT. Using the “refresh_token” grant creates an `OAuth2Authentication` object in `refreshAccessToken(…)` by calling `tokenStore.readAuthenticationForRefreshToken(refreshToken);`. This object doesn’t contain information about the grant type. 
My JWT contains user data and I need this grant type info in `JwtAccessTokenConverter` to reload this data from database via `UserDetailsService` to update the data that potentially changed during the “Access Token session”. This information is important, because I just need to reload data from database if the refresh token grant is used (all other grant types already loaded the data from database at this point).

**Comment by dsyer** [comment]
For the sake of clarity, there are 2 grant types if you are refreshing an access token - the current request (presumably "refresh_token") and the original one that granted the token. The original grant type is still there (e.g. "password") in the `OAuth2Request` if you don't use the `JwtTokenStore`, but is missing in the JWT case (so that's an issue). 

The fact that the token is being refreshed appears not to be accessible to the `TokenEnhancer` for any `TokenStore` implementation. That makes sense since I don't see why it should depend on the token store, but it's still an issue (albeit independent of the first one).

See also discussion in #401 for details of the use case.
