### ISSUE TITLE
TokenEndPoint problem bind HttpMethod parameter

### ISSUE THREAD

**Issue by oassuncao** [spring-projects/spring-security-oauth#413]
In TokenEndPoint class on version 2.0.6 is added the functionality to support others httpMethods, and receive a parameter with HttpMethod. I'm using Spring 3 and in this version the Spring can't bind this parameter and the value is NULL and always I receive the exception HttpRequestMethodNotSupportedException, See the code below:

```
@RequestMapping(value = "/oauth/token")
	public ResponseEntity<OAuth2AccessToken> getAccessToken(Principal principal, @RequestParam
	Map<String, String> parameters, HttpMethod requestMethod) throws HttpRequestMethodNotSupportedException {

		if (!allowedRequestMethods.contains(requestMethod)) {
			throw new HttpRequestMethodNotSupportedException(requestMethod.toString());
		}

               ....
}
```

**Comment by dsyer** [comment]
Spring 3 doesn't bind `HttpMethod` in a `@RequestMapping`?

**Comment by oassuncao** [comment]
Yes, you can see this information in the documentation, Only in Spring 4 you can bind HttpMethod
Spring 3
http://docs.spring.io/spring/docs/3.2.13.RELEASE/spring-framework-reference/html/mvc.html#mvc-ann-arguments

Spring 4
http://docs.spring.io/spring/docs/current/spring-framework-reference/html/mvc.html#mvc-ann-arguments

**Comment by dsyer** [comment]
I guess Spring 3 is not a dependency of this project, so it' snot really a surprise it doesn't work. The easiest way to get it to work is to simply not support anything other than POST anyway (which ironically is what @ccampo133 wanted in #327). 

I don't think we really want to commit to always supporting old versions of Spring, but this on the face of it a small thing to change (even though it might have a big effect on people who are misusing the token endpoint). Anyone else got opinions?

**Comment by oassuncao** [comment]
To resolve my problem I do this workaround bellow. In the version 2.0.5 the Spring OAuth works fine with Spring 3.

```
        @Override
        public void configure(AuthorizationServerEndpointsConfigurer endpoints) throws Exception {
            ...
            endpoints.allowedTokenEndpointRequestMethods().getAllowedTokenEndpointRequestMethods().add(null);
        }
```

**Comment by ccampo133** [comment]
The solution that set the default request method to POST, but still allowed other HTTP request methods, was to prevent any users who were using GET, PUT, etc. from completely breaking their set up, per the request of @dsyer . That being said, technically POST is the only method supported by the token endpoint in the OAuth 2 spec, and I still believe that should be enforced.

We could still resolve this issue by injecting `HttpServletRequest` instead of `HttpMethod`, as that is supported by Spring 3, and then using that to get the HTTP request method. I do agree though, allowing only POST is the cleanest (and easiest) solution :)

Best,
