### ISSUE TITLE
JWT: Client credentials token authorities lost when authenticating (Version 2.0.7)

### ISSUE THREAD

**Issue by ebrigand** [spring-projects/spring-security-oauth#506]
With a JWT token (`{"alg":"HS256"}{"scope":["read"],"exp":1433926194,"authorities":["ROLE_XXX_CLIENT"],"jti":"7dd36a90-745b-4fb1-b8f7-1778d6ffa41b","client_id":"myClient"}4:ßnRðòd<UQÁïvz»ZMFýó`) coming from a client credentials authentication, when we want to authenticate with it, we lost authorities. Bug looks like coming from the `super(null)` of `PreAuthenticatedAuthenticationToken`

In `OAuth2AuthenticationProcessingFilter` we have:

```
public void doFilter(ServletRequest req, ServletResponse res, FilterChain chain) throws IOException, ServletException {
...
Authentication authentication = tokenExtractor.extract(request);
..
}
```

`tokenExtractor` is a `BearerTokenExtractor` so extract code is:

```
@Override

    public Authentication extract(HttpServletRequest request) {
        String tokenValue = extractToken(request);
        if (tokenValue != null) {
            PreAuthenticatedAuthenticationToken authentication = new PreAuthenticatedAuthenticationToken(tokenValue, "");
            return authentication;
        }
        return null;
    }
```

The constructor `PreAuthenticatedAuthenticationToken` is like this:

```
public PreAuthenticatedAuthenticationToken(Object aPrincipal, Object aCredentials) {

    super(null);
    this.principal = aPrincipal;
    this.credentials = aCredentials;
}
```

Then the `super(null)` is:

```
public AbstractAuthenticationToken(Collection<? extends GrantedAuthority> authorities) {

        if (authorities == null) {
            this.authorities = AuthorityUtils.NO_AUTHORITIES;
            return;
        }

        for (GrantedAuthority a: authorities) {
            if (a == null) {
                throw new IllegalArgumentException("Authorities collection cannot contain any null elements");
            }
        }
        ArrayList<GrantedAuthority> temp = new ArrayList<GrantedAuthority>(authorities.size());
        temp.addAll(authorities);
        this.authorities = Collections.unmodifiableList(temp);
    }
```

So authorities are lost by `super(null)` in `PreAuthenticatedAuthenticationToken`, looks like a bug !???

**Comment by dsyer** [comment]
There are no authorities available at that stage in the `OAuth2AuthenticationProcessingFilter`. If the client has authorities and they don't end up in the final `OAuth2Authentication` we need to look at where that is created (in a `ResourceServerTokenServices`). I'm not sure which one you are using, but since it is a JWT token the default would be have a `JwtTokenStore` ultimately responsible for extracting the data from the token using an `AcecssTokenConverter`. The current version on master has code explicitly to transfer authorities to a client authentication (https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/token/DefaultAccessTokenConverter.java#L137). Are you using that version (I believe it is in 2.0.7 as well)?

**Comment by ebrigand** [comment]
Yes 2.0.7.

**Comment by dsyer** [comment]
Great, thanks for the update.
