### ISSUE TITLE
How to change the error response for TokenEndpoint?

### ISSUE THREAD

**Issue by miguelchico** [spring-projects/spring-security-oauth#582]
I have a question regarding the TokenEndpoint response error.
I'm trying to unify all error responses for my application but I can´t override the error response for TokenEndpoint.

The response I´m looking for is completly different than the actual sent by the TokenEndpoint. I want something like:

```
{
  "status": "UNAUTHORIZED",
  "code": 40102,
  "message": "Invalid Grant",
  "path": "/oauth/token",
}
````

but I can´t obtain that response using the exceptionTranslator because the response shoud be a OAuth2Exception and I can´t include these fields inside OAuth2Exception.

Do you have any suggestion?

**Comment by SlimeQ** [comment]
I have 2!

[This is my current solution.](https://gist.github.com/SlimeQ/c388c18bada5e48f9a9e) Notice my hacking up of the commence function, so that it never calls doHandle. this is key. For my purposes, I just wanted all auth errors to redirect to login, so this works fine (aside from the occasional infinite-redirect, but i've mostly sorted that out).

You can also use aspects for this. The general idea is to create a wrapper so you can override its behavior. I haven't gotten it working too well yet, but it's certainly an option. [This is all I have](https://gist.github.com/SlimeQ/828ade97f95101a35a82) to show for this. currently it just wraps any exception handler, but you can modify the parameters of the Around annotation to do whatever you'd like.

**Comment by michaeltecourt** [comment]
The TokenEndpoint response follow the [OAuth 2.0 specification](https://tools.ietf.org/html/rfc6749#section-5.2). The whole authorization server (authorize+token endpoint) must follow the spec as strictly as possible, or what's the point in using a standard ? 
You could hack another response format by implementing another `OAuth2AuthenticationEntryPoint` and `OAuth2AccessDeniedHandler` (in the end it's about tweaking the response of `WebResponseExceptionTranslator` into something else than `OAuth2Exception`), but I would strongly advise against it, and I highly doubt the framework was built to allow you to do it easily on the **authorization server** side.

On the other hand, you can do mostly what you want on the **resource server** side (your HTTP API that use OAuth 2.0 tokens as a security).
I've just sent a [pull request](https://github.com/spring-projects/spring-security-oauth/pull/598) that should ease the pain of customizing *resource server* error responses (if the change is accepted of course).
The idea is what I described above, which is making `WebResponseExceptionTranslator<T>` generic in order to easily return something else than an `OAuth2Exception`.

**Comment by SlimeQ** [comment]
@michaeltecourt the motivation for customizing error responses is that we're using oauth for both the browser front-end of our project and the api backend; ideally the browser user should never see raw xml output and our api responses are standardized to json. is this an unnecessary abuse of the oauth standard? is there a better way to do this?

**Comment by nklnandu** [comment]
I have implemented the WebResponseExceptionTranslator  but from the Tokenendpoint its not taking my customTranslator . Always taking as DefaultWebResponseExceptionTranslator

**Comment by michaeltecourt** [comment]
That's because the TokenEndpoint follows strictly the OAuth 2.0 specification. If it returned anything else than OAuth 2.0 errors, it wouldn't be OAuth 2.0.
There is no valid reason to change the TokenEndpoint error format, unless you're planning on writing a new protocol that derrives from OAuth 2.0.

Only your resource server (API) could have its own error model.

**Comment by nklnandu** [comment]
I agree. How I can customize my error response.? If i implement the WebResponseExceptionTranslator . In which config i have to give my customTranslator ?

**Comment by SlimeQ** [comment]
@nklnandu if you simply include your own DefaultWebResponseExceptionTranslator in the expected package (copied from the default WebResponseExceptionTranslator found [here](https://github.com/spring-projects/spring-security-oauth/blob/1b2ae987e9486a875b40424f18bb785baf0b898c/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/error/DefaultWebResponseExceptionTranslator.java)) it will override the default class and your code will be used. this might not be best practice but it will work in most situations where you find yourself fighting with the framework.

**Comment by nklnandu** [comment]
It's not working if i include my ownlike CustomWebResponseExceptionTranslator( all the content is copied from default) .The Issue is from the TokenPoint  Its always i am seeing the DefaultWebResponseExceptionTranslator (framework class instance is created.) Some how if i make my own WebResponseExceptionTranslator there it will enhance all other stuff. 
Thanks for your help .. 
Any help is appreciated

**Comment by SlimeQ** [comment]
try naming it DefaultWebResponseExceptionTranslator instead of CustomWebResponseExceptionTranslator

**Comment by nklnandu** [comment]
Here is the my code

**Comment by nklnandu** [comment]
@Bean(name = "exceptionTranslator")
	 public  DefaultWebResponseExceptionTranslator getWebResponseExceptionTranslator() {
		 DefaultWebResponseExceptionTranslator customExceptionTranslator = new DefaultWebResponseExceptionTranslator();
	        return customExceptionTranslator;
	    }
	 
	 
	 
	@Bean(name = "clientAuthenticationEntryPoint")
	public CustomOAuth2AuthenticationEntryPoint getClientAuthenticationEntryPoint() throws Exception {
		
		CustomOAuth2AuthenticationEntryPoint customOAuth2AuthenticationEntryPoint =  new CustomOAuth2AuthenticationEntryPoint();
		customOAuth2AuthenticationEntryPoint.setExceptionTranslator(getWebResponseExceptionTranslator());
		customOAuth2AuthenticationEntryPoint.setExceptionRenderer(getCustomExceptionRenderer());
		return customOAuth2AuthenticationEntryPoint;
	}

I am not sure. If i have my break point in Tokenpoint means i can see only the framework class not my custom class. 

Any configuration am i missing to make it happen.

**Comment by SlimeQ** [comment]
is your DefaultWebResponseExceptionTranslator class in the proper package like `package org.springframework.security.oauth2.provider.error;`? if it's in the same package as the old one the framework will pick it up with no config needed.

**Comment by nklnandu** [comment]
Yes. But it does not help on that. We may need to do some proper way to pickup our own class.

**Comment by rwinch** [comment]
It's an API response. You should translate it and display something meaningful to the user.
