### ISSUE TITLE
Wrong "order" of endpoint mapping for OAuth auto configuration in MVC environment

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security-oauth#613]
In MVC web environment Resource endpoint mapping and OAuth2 endpoint mapping have the same order so resource endpoint prevents oauth2 endpoints.
@EnableWebMvc causes WebConfigurationSupport to provide a resource endpoint. When oauth2 authorization server is to be used, oauth2FrameworkHandlerMapping bean must be positioned higher than the resource endpoint.
Currently, this can be overcomed by adding a custom BeanPostProcessor to set order of the bean to a higher value manually

Original Report: https://jira.spring.io/browse/SEC-2938

**Comment by dsyer** [comment]
Strange that this doesn't show up in any of the samples because as far as I can tell the `FrameworkEndpointHandlerMapping` and the `ResourceHandlerRegistry` (from MVC) have always had the same order.

I don't think the `BeanPostProcessor` is necessary (Web MVC allows customization of the resource handler mapping order).
