### ISSUE TITLE
Support setting a RedirectResolver in the AuthorizationServerEndpointsConfigurer

### ISSUE THREAD

**Issue by ractive** [spring-projects/spring-security-oauth#696]
I'd want to be able to set a special RedirectResolver using java config with the AuthorizationServerEndpointsConfigurer.

**Comment by sfussenegger** [comment]
@dsyer would it be possible to get this into the next 2.0.* release? This is fully backward compatible. The Travis build of the PR is only broken because of the log length exceeding the allowed limit: "The log length has exceeded the limit of 4 MB [...] The job has been terminated". Locally, the build works for me.

I'm asking because #746 introduced a change to the default behavior and this feature would help to restore the previous behavior. The documentation ticket #760 isn't helping as I can't find any documentation.

**Comment by jgrandja** [comment]
@ractive I'll merge this PR but I'll need you to add some tests first.

@sfussenegger I'll see what I can do to merge this into the next 2.0.x release.

As a temporary workaround, try this:

```
@Configuration
@EnableAuthorizationServer
public class AuthorizationServerConfig extends AuthorizationServerConfigurerAdapter {
...
...
...
	@Autowired
	public void configureAuthorizationEndpoint(AuthorizationEndpoint authorizationEndpoint) {
		DefaultRedirectResolver redirectResolver = new DefaultRedirectResolver();
		redirectResolver.setMatchPorts(false);
		authorizationEndpoint.setRedirectResolver(redirectResolver);
	}
```

**Comment by jgrandja** [comment]
Closing in favor of #1190
