### ISSUE TITLE
JDBCTokenStore Access token can not be converted back to String

### ISSUE THREAD

**Issue by kyeljmd** [spring-projects/spring-security-oauth#777]
I am using the JDBCTokenStore for my oauth2. The token is generated by java, however when other languages such as ruby, access the token. they can't seem to parse it to string. and also, I can't also decode the byte data to String format using Postgresql. Do we have support for this?

**Comment by benkiefer** [comment]
The default implementation of the JdbcTokenStore shoves access tokens, spring authentication objects, and refresh tokens into the database as Java serialized objects, which you won't be able to deserialize using another programming language (or future versions of Spring Security because the bump the serialization uid on every minor release for some of their objects).

**Comment by kyeljmd** [comment]
Oh I see. If that's the case my team and I should use JWT as our Token. Thank you!
