### ISSUE TITLE
Make OAuth2 expression handlers available to authorization server config

### ISSUE THREAD

**Issue by Fitzoh** [spring-projects/spring-security-oauth#792]
`AuthorizationServerSecurityConfigurer` has access Strings which can be used to set the security of the check_token and token_key endpoints.  These currently only have access to the base spring security expression language, and not the OAuth2 expression methods.

A use case I recently ran into was a requirement to only allow principals authenticated through client credentials to hit the check_token endpoint.  This is made difficult by OAuth2 expressions not being enabled by default, and there not being a straightforward way to add them.

An existing workaround is available [here](http://stackoverflow.com/questions/37980825/configuring-spring-oauth2-expression-handler-methods-for-authorization-server-en)

**Comment by jgrandja** [comment]
Hi @Fitzoh. I looked at your existing workaround on SO and I'm wondering if that really works?

The reason I'm asking is because the expression `#oauth2.isClient()` evaluates the call to `OAuth2SecurityExpressionMethods.isClient()` which checks to see if the current `Authentication` is of type `OAuth2Authentication`.

However, an  `OAuth2Authentication` is created, after a successful authentication, on a _Resource Server_ **NOT** the _Authorization Server_ through the `OAuth2AuthenticationProcessingFilter`.

Currently, the `OAuth2AuthenticationProcessingFilter` is only being used on the _Resource Server_ so it would also need to be setup as a pre-auth filter on the _Authorization Server_ targeted for the `check_token` endpoint for the expression to actually work. This would require a lot more work than what you have on your SO post.

Can you please confirm if your workaround does work? If so, can you provide me a sample as well?
Thanks.

**Comment by Fitzoh** [comment]
@jgrandja I'll see what I can dig up (June feels like a looong time ago).
It's possible that it was working for me due to having the Authorization Server and Resource server in the same application.
 I can see how that would cause issues for a standalone Auth server.

**Comment by jgrandja** [comment]
Hi @Fitzoh. I haven't heard back from you so I'm assuming all is good?
I'm going to close this issue but if you need further help with this I'd be happy to re-open it if you can provide a sample re-producing the issue.
Thanks.
