### ISSUE TITLE
Possible CSRF detected - state parameter was required but no state could be found

### ISSUE THREAD

**Issue by baiyangliu** [spring-projects/spring-security-oauth#822]
I can run [oauth2](https://github.com/spring-projects/spring-security-oauth/tree/master/samples/oauth2) very well by default.
But,it may produce a error "Possible CSRF detected - state parameter was required but no state could be found",when i put the tonr project to tomcat ROOT

**Comment by dsyer** [comment]
Probably the server and client are eating each other's cookies? They have have to be on different hosts and/or paths to keep the cookies separate in the browser.

**Comment by aiboogie** [comment]
Sorry to reopen this discussion, I still get this one, different tomcats, different hostnames and different app contexts.
Any advice? Is there a way to put stateMandatory on false from the spring config ?
Thanks in advance.

**Comment by johnhunsley** [comment]
I'm running Spring Boot 2.1.0 and I'm getting this same issue. I'm running my Auth Server, Client App and Resource Server on different root context paths and different ports. I have tried changing the cookie names but I still see the problem discussed in [#322](https://github.com/spring-projects/spring-security-oauth/issues/322) 

As far as I can tell from debugging this the bug is in the state is not persisted because the OAuthClientContext is not session scoped.

**Comment by gcloeval** [comment]
I am also having this issue, spring boot 2. Anybody found a workaround?

**Comment by EtachGu** [comment]
I also get this Issue, Spring boot 2.1

**Comment by singharunkumar83** [comment]
This issue appeared only when I run two instances of this service.  Any solution or workaround?
