### ISSUE TITLE
Read returned JWT from a different attribute in response

### ISSUE THREAD

**Issue by hildo** [spring-projects/spring-security-oauth#909]
Hi.  I've been using spring-security-oauth2 with Spring Security 4.1.3 for the last few months successfully.  During that time, I have been using a custom implementation of an Auth Server as a temporary measure, based on Spring's reference implementation (as described in the [doco](http://projects.spring.io/spring-security-oauth/docs/oauth2.html)).  With that Auth Server, a JWT has been returned to the ssoClient.  Calling clients have been using auth_code, clientCredentials and password grant types to get the JWT and everything has been happy.

As I mentioned, this was a temporary measure.  Moving forward, we would like to use Azure Active Directory as our Authorization Server instead of our own.  So, I have been following [their instructions](https://docs.microsoft.com/en-in/azure/active-directory/active-directory-v2-protocols-oauth-code) for using their endpoints as OAuth 2.0 resources.  Specifically, I think they support OpenId Connect as their setup.

I have been able to retrieve an Auth  Code, and have been able to get an Access Token.  However, where the current version is falling over is how the accessTokenUri is returning it's values.  The data structure returned from the accessTokenUri returns both an access_token and an id_token, and the value in the id_token is the JWT.   This is what it looks like when parsed as an instance of the DefaultOAuth2AccessToken object

![image](https://cloud.githubusercontent.com/assets/1204224/20581930/00b03be2-b228-11e6-8af5-ec65515ed6ea.png)

As I see it, the code in the OAuth2ClientAuthenticationProcessingFilter presumes that the JWT it needs to decode is in the access_token attribute, and this all falls over.

I've made some changes locally so that the value from the id_token value in additional information is used instead, and it works.  I need to make additional changes to validate the token but I hope to be able to do that next.

I'm happy to create a pull request to submit a potential change to support reading from either access_token or id_token.  But, before I do, I was hoping someone could tell me if making changes to this is the correct approach or if I should be doing something else.  For what I need to do, I think this should be sufficient.  But I am happy to defer to the expertise of this group.

**Comment by hildo** [comment]
I wanted to mark this as a Question, but it won't let me.

Here is the start of the changes I have checked locally in my own fork

https://github.com/spring-projects/spring-security-oauth/compare/master...hildo:idTokenChanges?expand=1

This is not complete.   I had hoped that I could use a property value to define the AccessTokenValueReader but what I have there doesn't work.  But the basics of what I was hoping to add works for me when I hard-code the reader for Azure's reply (I will not create any pull request that hard-codes anything).

**Comment by jgrandja** [comment]
Hi @hildo 

The current implementation of Spring Security OAuth implements the [OAuth 2.0 spec](https://tools.ietf.org/html/rfc6749). 

It does NOT implement the [Open ID Connect Core Spec](http://openid.net/specs/openid-connect-core-1_0.html).

The [`id_token`](http://openid.net/specs/openid-connect-core-1_0.html#IDToken) is part of the Open ID Connect Core Spec.

The reason you're seeing the JWT (id_token) in `DefaultOAuth2AccessToken.additionalInformation` is because `OAuth2AccessTokenJackson2Deserializer` will populate any additional attributes that are not part of the expected [OAuth2 Successful Response](https://tools.ietf.org/html/draft-ietf-oauth-v2-22#section-5.1).

As a FYI, we are currently working on a [re-write of Spring Security OAuth2](https://github.com/spring-projects/spring-security/issues/3907) with support for OpenID Connect. We are expecting to release the first milestone later in Dec or sometime in Jan. This release is strictly focusing on the client side (which is what you need). We haven't decided if we're going to do a re-write of the server side. Also, the current Spring Security OAuth is in maintenance mode now as we're focusing our efforts on the re-write.

I'm going to close this issue as I feel I have answered your question. But if you have any further questions please let me know.
Thanks.
