### ISSUE TITLE
Add TokenStore supporting JWT verification using JWK

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security-oauth#977]
It would be very useful to have a `TokenStore` implementation that verifies a **JWT** using a **JSON Web Key (JWK)**.

The main goal of this implementation would be to verify a JWT using the corresponding JWK. The JWK used for verification is matched using the `kid` header parameter of the JWT and the `kid` attribute of the JWK.

The implementation would be responsible for fetching the JWK Set (the set of available JSON Web Key's) from the supplied URL.

## Related Specifications

[JSON Web Token (JWT)](https://tools.ietf.org/search/rfc7519)

[JSON Web Key (JWK)](https://tools.ietf.org/html/rfc7517)

[JSON Web Signature (JWS)](https://tools.ietf.org/html/rfc7515)

[JSON Web Encryption (JWE)](https://tools.ietf.org/html/rfc7516)

[JSON Web Algorithms (JWA)](https://tools.ietf.org/html/rfc7518)

**Comment by yelhouti** [comment]
Thanks for the great work, could we have something like: jwks-uri in the application.yml/properties that create the store authomaticaly.
this should be the default way for validating id_token. othere fields are now mendatory in the .yml we shoudl have the choice between them and this.
thanks

**Comment by jgrandja** [comment]
@yelhouti  This question should be posted in the Spring Boot GitHub as it's related to custom configuration properties in application.yml.

On that note, Spring Boot 1.5.2 has added a new configuration property related to this [issue](https://github.com/spring-projects/spring-boot/issues/8350)

```
security.oauth2.resource.jwk.key-set-uri: [URL to JWK Set]
```

You mentioned the following...

> this should be the default way for validating id_token

Please note that Spring Security OAuth currently does not provide support for OpenID Connect so there is no validation/verification of `id_token`.

We are currently working on a re-write of OAuth and integrating it into Spring Security proper and it will provide support for OpenID Connect. You can track the issue [here](https://github.com/spring-projects/spring-security/issues/3907)

**Comment by yelhouti** [comment]
Indeed I forgot to update spring boot in gradle.properties: springBootVersion = '1.5.2.RELEASE'
Good luck for the re-write, you might want to have a look a this repo: https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server
Hope it helps or you already know it.
thanks and keep up the good work.

**Comment by jgrandja** [comment]
Thanks @yelhouti. Yes, I have already looked at MITREid Connect.

**Comment by sdoxsee** [comment]
@jgrandja I'm trying out the new support for JWK format. I'm trying to consume a key set in the following form:
```
{
   "keys": [
      {
         "kty": "RSA",
         "e": "AQAB",
         "kid": "rsa1",
         "alg": "RS256",
         "n": "qt6yOiI_wCoCVlGO0MySsez0VkSqhPvDl3rfabOslx35mYEO-n4ABfIT5Gn2zN-CeIcOZ5ugAXvIIRWv5H55-tzjFazi5IKkOIMCiz5__MtsdxKCqGlZu2zt-BLpqTOAPiflNPpM3RUAlxKAhnYEqNha6-allPnFQupnW_eTYoyuzuedT7dSp90ry0ZcQDimntXWeaSbrYKCj9Rr9W1jn2uTowUuXaScKXTCjAmJVnsD75JNzQfa8DweklTyWQF-Y5Ky039I0VIu-0CIGhXY48GAFe2EFb8VpNhf07DP63p138RWQ1d3KPEM9mYJVpQC68j3wzDQYSljpLf9by7TGw"
      }
   ]
}
```
(from [https://mitreid.org/jwk](https://mitreid.org/jwk) and as defined in the [spec](https://tools.ietf.org/html/rfc7517#section-4))

However, it seems that spring only supports PEM-encoded "value" entries (as [documented](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-security.html#boot-features-security-oauth2-resource-server) in spring-boot).

Is the official JWK format supported? I only see the PEM flavour in Spring/Cloudfoundry products.

My workaround is that I manually take the JWK for every environment, convert it to PEM, and add it's value to my application.yml as key-value--since I can't easily make my JWK on my authorization use "value" (nor do I want to).

Thanks!
